### ISSUE TITLE
Cannot read property 'shift' of null

### ISSUE THREAD

**Issue by gOmp** [vittee/simcom#1]
Using Raspberry with sim900

```
sudo node node_modules/simcom/example/read_sms
/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:155
                throw e;
                      ^
TypeError: Cannot read property 'shift' of null
    at SimCom.<anonymous> (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/lib/simcom.js:227:25)
    at /home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/lib/simcom.js:194:29
    at _fulfilled (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:796:13)
    at /home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:604:44
    at runSingle (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:137:13)
    at flush (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)
```

same type of errors occur with few other examples like all_sms.js & send_sms.js, while sim800.js & open.js works fine. 

```
sudo node all_sms
/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:155
                throw e;
                      ^
TypeError: Cannot read property 'map' of null
    at SimCom.<anonymous> (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/lib/simcom.js:214:15)
    at /home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/lib/simcom.js:194:29
    at _fulfilled (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:796:13)
    at /home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:604:44
    at runSingle (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:137:13)
    at flush (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)
```

```
 sudo node send_sms "+123456789" "yo"
ERR [TypeError: Cannot read property 'shift' of null]
/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:155
                throw e;
                      ^
TypeError: Cannot read property 'shift' of null
    at SimCom.<anonymous> (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/lib/simcom.js:240:16)
    at /home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/lib/simcom.js:194:29
    at _fulfilled (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:796:13)
    at /home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:604:44
    at runSingle (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:137:13)
    at flush (/home/pi/node_lab/gsm_sandbox/gsm2_simcom/node_modules/simcom/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)
```

**Comment by vittee** [comment]
Thanks, 

It might take sometimes since I do not have any RPi attached with sim800 right now.

**Comment by ptorrent** [comment]
Hey !

Any news ?

**Comment by vittee** [comment]
@ptorrent @gOmp 
I was on a team developing a product which uses SIM800 and I was responsible for writing this Node.js Module and one of team member owns the device.

Unfortunately, I don't have the device to try, any longer.

Please feel free to fork my module.
